---
# If true, only one thread will be used (which decreases performance)
debug: false

# If true, TeX values for tables will be copied to the clipboard
texify: false

# Language is needed for stopwords (english/german)
language: english

# Folder names
casebase_folder: data/case-base/english/microtexts-plain
queries_folder: data/queries/english/microtexts-plain
embeddings_folder: data/embeddings/english
candidates_folder: data/candidates/microtexts
results_folder: data/results

# File names
embeddings_supervised:
  - infersent.pkl
  - use-d
  - use-t
sif_weightfile: data/sif/enwiki_vocab_min200.txt
infersent_w2v_file: glove.txt

# Web server config
flask_host: 0.0.0.0
flask_port: 8888

# Default values (can be adjusted in web app)
operations:
  - mean
embeddings_filter:
  - use-t

similarity_method: cosine
token_weighting: none
sif_parameter: 0.001

similarity_threshold: 0.0
retrieval_limit: 10

export_results: false
export_results_aggregated: true
candidates_max_rank: 3

perform_mac: true
perform_fac: true
ideal_mac: false
a_star_queue_limit: 10000

stemming: false
ignore_stopwords: false

use_schemes: false
use_ontology: false

number_of_runs: 1

app_name: "recap-utr/argument-graph-retrieval"
